### ISSUE TITLE
PostCSS exclude option doesn't seem to work

### ISSUE THREAD

**Issue by jnsandrew** [mrmckeb/typescript-plugin-css-modules#109]
**Describe the bug**
When setting the `useConfig` setting to `true`, and using the `excludePlugins` option to exclude async plugins, the plugin errors and doesn't show correct types.

**To Reproduce**
1. Set up as per documentation
2. Add `postcss-nested` as a plugin (this works)
3. Add a different plugin e.g. `'postcss-mixins'` or `'postcss-import'` and try to exclude
4. Restart VS Code (this seems to be important?)
5. Typings stop working for .css files / css modules

**Expected behavior**
Typings should still work because the offending plugins should have been excluded

**Additional context**

**tsconfig:**
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "baseUrl": ".",
        "declaration": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "importHelpers": true,
        "jsx": "react",
        "module": "esnext",
        "moduleResolution": "node",
        "noImplicitAny": false,
        "lib": ["es2015", "dom", "es5", "scripthost", "es2020.string", "esnext"],
        "paths": {
            "@trayio/connector-discovery": ["libs/connector-discovery/src/index.ts"],
            "@trayio/user-tracking": ["libs/user-tracking/src/index.ts"],
            "@trayio/workflow-canvas": ["libs/workflow-canvas/src/index.ts"]
        },
        "plugins": [
            {
                "name": "typescript-plugin-css-modules",
                "options": {
                    "customMatcher": "\\.css$",
                    "postCssOptions": {
                        "useConfig": true,
                        "excludePlugins": [
                            "postcss-import",
                            "postcss-mixins",
                            "postcss-color-function"
                        ]
                    }
                }
            }
        ],
        "rootDir": ".",
        "skipLibCheck": true,
        "skipDefaultLibCheck": true,
        "sourceMap": true,
        "strictNullChecks": true,
        "target": "ES5",
        "typeRoots": ["node_modules/@types"],
        "esModuleInterop": true
    },
    "exclude": ["node_modules", "build/", "e2e/", "tmp"]
}
```

**.postcssrc.js**
```
module.exports = {
    map: false,
    plugins: {
        'postcss-import': {
            path: 'packages/core/assets/styles',
        },
        'postcss-mixins': {
            mixinsDir: 'packages/core/assets/mixins',
        },
        'postcss-nested': {},
        'postcss-nesting': {},
        'postcss-color-function': {},
    },
};

```

The plugin only works when I remove `postcss-import`, `postcss-mixins` and `postcss-color-function` from the list ^
I'm not familiar with writing TS plugins. I had a look at the TS server logs and I think the most notable section is this error spit out by the plugin. It seems like it's still trying to use the plugins I have tried to exclude (assuming they are async plugins in this case based on #46 ). 

```javascript
Info 2087 [10:22:30.882] [typescript-plugin-css-modules] Failed Error: Use process(css).then(cb) to work with async plugins
Info 2088 [10:22:30.895] [typescript-plugin-css-modules] Stack trace: Error: Use process(css).then(cb) to work with async plugins
    at LazyResult.sync (/Users/andrewjones/Sites/app/node_modules/postcss/lib/lazy-result.js:284:15)
    at LazyResult.get (/Users/andrewjones/Sites/app/node_modules/postcss/lib/lazy-result.js:405:19)
    at Object.exports.getClasses (/Users/andrewjones/Sites/app/node_modules/typescript-plugin-css-modules/lib/helpers/getClasses.js:101:29)
    at Object.exports.getDtsSnapshot (/Users/andrewjones/Sites/app/node_modules/typescript-plugin-css-modules/lib/helpers/getDtsSnapshot.js:15:32)
    at Object.ts.createLanguageServiceSourceFile (/Users/andrewjones/Sites/app/node_modules/typescript-plugin-css-modules/lib/index.js:103:51)
    at acquireOrUpdateDocument (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:117837:37)
    at Object.acquireDocumentWithKey (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:117810:20)
    at getOrCreateSourceFileByPath (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:143424:41)
    at Object.getOrCreateSourceFile [as getSourceFile] (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:143376:24)
    at findSourceFile (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:104161:29)
    at processImportedModules (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:104502:25)
    at findSourceFile (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:104209:17)
    at processImportedModules (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:104502:25)
    at findSourceFile (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:104209:17)
    at /Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:104038:85
    at getSourceFileFromReferenceWorker (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:104005:34)
    at processSourceFile (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:104038:13)
    at processRootFile (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:103861:13)
    at /Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:102785:60
    at Object.forEach (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:188:30)
    at Object.createProgram (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:102785:16)
    at synchronizeHostData (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:143341:26)
    at Proxy.getProgram (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:143433:13)
    at ConfiguredProject.Project.updateGraphWorker (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:148278:53)
    at ConfiguredProject.Project.updateGraph (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:148211:42)
    at ConfiguredProject.updateGraph (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:149145:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:150849:25)
    at ProjectService.assignProjectToOpenedScriptInfo (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:151747:44)
    at /Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:152070:97
    at Object.flatMap (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:152070:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:153089:46)
    at /Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:154962:88
    at IOSession.Session.executeWithRequestId (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:154953:28)
    at IOSession.Session.executeCommand (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:154962:33)
    at IOSession.Session.onMessage (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:154986:35)
    at Interface.<anonymous> (/Users/andrewjones/Sites/app/node_modules/typescript/lib/tsserver.js:157202:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by mrmckeb** [comment]
Hi @jnsandrew, I just saw I missed this issue, sorry.

It does seem like your plugins are not being excluded, as you said. The `async` error is the reason the exclude list exists, which is passed into the `filter` plugin.
https://github.com/mrmckeb/typescript-plugin-css-modules/blob/main/src/index.ts#L69

On a side note, it's a technical limitation in the way TypeScript handles plugins like this that prevents us from being able to process asynchronously.

Unfortunately, I've tried a few times and I'm not able to replicate this. Are you able to supply a reproduction?

**Comment by jnsandrew** [comment]
Thanks for getting back to me - to be honest I had forgotten about this myself. I've just been on a bit of an upgrade mission and between upgrades to Webpack 5, PostCSS 8, Typescript 4.1, and (probably) a newer version of this plugin, it seems to have sorted itself out. So will close this.

**Comment by mrmckeb** [comment]
No problem, and sorry again I took so long - glad everything is solved!
