### ISSUE TITLE
VS Code: Failed to load 'typescript-plugin-css-modules' from <extension>: Error: Could not resolve JS module 'typescript-plugin-css-modules'

### ISSUE THREAD

**Issue by talentlessguy** [mrmckeb/typescript-plugin-css-modules#190]
**Describe the bug**

On a clean project with latest typescript the plugin doesn't work with VS Code. Might be because it's pnpm, might be something else. It worked with older version of the plugin and ts.

**To Reproduce**

1. `pnpm init`
2. `pnpm i next react react-dom && pnpm i -D typescript @types/react @types/node typescript-plugin-css-modules`
3. create a css file and import a classname to any ts(x) file

package.json:

```json
{
  "scripts": {
    "dev": "next dev",
    "start": "next start",
    "build": "next build"
  },
  "dependencies": {
    "next": "^13.1.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "^18.11.18",
    "@types/react": "^18.0.26",
    "typescript": "^4.9.4",
    "typescript-plugin-css-modules": "^4.1.1"
  }
}
```

**Expected behavior**

Plugin should work out of the box.

**Desktop (please complete the following information):**

- OS: Linux

**Additional context**

TS Server Log:

```js
Info 0    [18:12:32.155] Starting TS Server
Info 1    [18:12:32.156] Version: 4.9.4
Info 2    [18:12:32.156] Arguments: /usr/lib/electron19/electron /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /tmp/vscode-typescript1000/187b095cf8baa5cf4898/tscancellation-afffc27baf7504a6428d.tmp* --logVerbosity terse --logFile /home/v1rtl/.config/Code - OSS/logs/20230113T171654/window1/exthost/vscode.typescript-language-features/tsserver-log-rBjlZW/tsserver.log --globalPlugins typescript-deno-plugin,typescript-styled-plugin,@vsintellicode/typescript-intellicode-plugin,ms-vsintellicode-typescript --pluginProbeLocations /home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0,/home/v1rtl/.vscode-oss/extensions/jpoissonnier.vscode-styled-components-1.7.0,/home/v1rtl/.vscode-oss/extensions/visualstudioexptteam.vscodeintellicode-1.2.30,/home/v1rtl/.vscode-oss/extensions/visualstudioexptteam.vscodeintellicode-1.2.30 --npmLocation "pnpm" --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
Info 3    [18:12:32.156] Platform: linux NodeVersion: 16 CaseSensitive: true
Info 4    [18:12:32.156] ServerMode: undefined syntaxOnly: false hasUnknownServerMode: undefined
Info 5    [18:12:32.176] Host information vscode
Info 6    [18:12:32.176] Host watch options changed to undefined, it will be take effect for next watches.
Info 7    [18:12:32.180] Search path: /home/v1rtl/Coding/ens/pages
Info 8    [18:12:32.182] For info: /home/v1rtl/Coding/ens/pages/register.tsx :: Config file name: /home/v1rtl/Coding/ens/tsconfig.json
Info 9    [18:12:32.182] Creating configuration project /home/v1rtl/Coding/ens/tsconfig.json
Info 10   [18:12:32.218] Config: /home/v1rtl/Coding/ens/tsconfig.json : {
 "rootNames": [
  "/home/v1rtl/Coding/ens/next-env.d.ts",
  "/home/v1rtl/Coding/ens/hooks/useRegisterENS.ts",
  "/home/v1rtl/Coding/ens/lib/constants.ts",
  "/home/v1rtl/Coding/ens/lib/utils.ts",
  "/home/v1rtl/Coding/ens/components/ConnectWidget.tsx",
  "/home/v1rtl/Coding/ens/components/InputENS.tsx",
  "/home/v1rtl/Coding/ens/components/Nav.tsx",
  "/home/v1rtl/Coding/ens/components/icons.tsx",
  "/home/v1rtl/Coding/ens/pages/_app.tsx",
  "/home/v1rtl/Coding/ens/pages/index.tsx",
  "/home/v1rtl/Coding/ens/pages/register.tsx"
 ],
 "options": {
  "target": 6,
  "lib": [
   "lib.dom.d.ts",
   "lib.dom.iterable.d.ts",
   "lib.esnext.d.ts"
  ],
  "allowJs": true,
  "skipLibCheck": true,
  "strict": false,
  "forceConsistentCasingInFileNames": true,
  "noEmit": true,
  "baseUrl": "/home/v1rtl/Coding/ens",
  "esModuleInterop": true,
  "module": 99,
  "downlevelIteration": true,
  "moduleResolution": 2,
  "resolveJsonModule": true,
  "isolatedModules": true,
  "preserveSymlinks": true,
  "jsx": 1,
  "incremental": true,
  "plugins": [
   {
    "name": "typescript-plugin-css-modules"
   }
  ],
  "configFilePath": "/home/v1rtl/Coding/ens/tsconfig.json"
 }
}
Info 11   [18:12:32.230] Enabling plugin typescript-plugin-css-modules from candidate paths: /home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0,/home/v1rtl/.vscode-oss/extensions/jpoissonnier.vscode-styled-components-1.7.0,/home/v1rtl/.vscode-oss/extensions/visualstudioexptteam.vscodeintellicode-1.2.30,/home/v1rtl/.vscode-oss/extensions/visualstudioexptteam.vscodeintellicode-1.2.30,/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js/../../..
Info 12   [18:12:32.230] Loading typescript-plugin-css-modules from /home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0 (resolved to /home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0/node_modules)
Info 13   [18:12:32.256] Loading typescript-plugin-css-modules from /home/v1rtl/.vscode-oss/extensions/jpoissonnier.vscode-styled-components-1.7.0 (resolved to /home/v1rtl/.vscode-oss/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules)
Info 14   [18:12:32.257] Loading typescript-plugin-css-modules from /home/v1rtl/.vscode-oss/extensions/visualstudioexptteam.vscodeintellicode-1.2.30 (resolved to /home/v1rtl/.vscode-oss/extensions/visualstudioexptteam.vscodeintellicode-1.2.30/node_modules)
Info 15   [18:12:32.261] Loading typescript-plugin-css-modules from /home/v1rtl/.vscode-oss/extensions/visualstudioexptteam.vscodeintellicode-1.2.30 (resolved to /home/v1rtl/.vscode-oss/extensions/visualstudioexptteam.vscodeintellicode-1.2.30/node_modules)
Info 16   [18:12:32.262] Loading typescript-plugin-css-modules from /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js/../../.. (resolved to /usr/lib/code/extensions/node_modules/node_modules)
Info 17   [18:12:32.263] Failed to load module 'typescript-plugin-css-modules' from /home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0/node_modules: Error: Could not resolve JS module 'typescript-plugin-css-modules' starting at '/home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0/node_modules'. Looked in: /home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0/node_modules/typescript-plugin-css-modules/package.json, /home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0/node_modules/typescript-plugin-css-modules.js, /home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0/node_modules/typescript-plugin-css-modules.jsx, /home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0/node_modules/typescript-plugin-css-modules/index.js, /home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0/node_modules/typescript-plugin-css-modules/index.jsx, /home/v1rtl/.vscode-oss/extensions/node_modules/typescript-plugin-css-modules/package.json, /home/v1rtl/.vscode-oss/extensions/node_modules/typescript-plugin-css-modules.js, /home/v1rtl/.vscode-oss/extensions/node_modules/typescript-plugin-css-modules.jsx, /home/v1rtl/.vscode-oss/extensions/node_modules/typescript-plugin-css-modules/index.js, /home/v1rtl/.vscode-oss/extensions/node_modules/typescript-plugin-css-modules/index.jsx, /home/v1rtl/.vscode-oss/node_modules/typescript-plugin-css-modules/package.json, /home/v1rtl/.vscode-oss/node_modules/typescript-plugin-css-modules.js, /home/v1rtl/.vscode-oss/node_modules/typescript-plugin-css-modules.jsx, /home/v1rtl/.vscode-oss/node_modules/typescript-plugin-css-modules/index.js, /home/v1rtl/.vscode-oss/node_modules/typescript-plugin-css-modules/index.jsx, /home/v1rtl/node_modules/typescript-plugin-css-modules/package.json, /home/v1rtl/node_modules/typescript-plugin-css-modules.js, /home/v1rtl/node_modules/typescript-plugin-css-modules.jsx, /home/v1rtl/node_modules/typescript-plugin-css-modules/index.js, /home/v1rtl/node_modules/typescript-plugin-css-modules/index.jsx, /home/node_modules/typescript-plugin-css-modules/package.json, /home/node_modules/typescript-plugin-css-modules.js, /home/node_modules/typescript-plugin-css-modules.jsx, /home/node_modules/typescript-plugin-css-modules/index.js, /home/node_modules/typescript-plugin-css-modules/index.jsx, /node_modules/typescript-plugin-css-modules/package.json, /node_modules/typescript-plugin-css-modules.js, /node_modules/typescript-plugin-css-modules.jsx, /node_modules/typescript-plugin-css-modules/index.js, /node_modules/typescript-plugin-css-modules/index.jsx
    at Object.resolveJSModule (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:44257:19)
    at sys.require (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:185768:49)
    at Project.resolveModule (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:173477:35)
    at /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:174624:36
    at Object.firstDefined (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:221:26)
    at Project.beginEnablePluginSync (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:174623:41)
    at ProjectService.requestEnablePlugin (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:178808:49)
    at Project.enablePlugin (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:174687:37)
    at ConfiguredProject.enablePluginsWithOptions (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:175358:30)
    at ProjectService.loadConfiguredProject (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:177076:25)
    at ProjectService.createAndLoadConfiguredProject (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:177028:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:177033:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:178119:44)
    at /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:178459:97
    at Object.flatMap (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:524:25)
    at ProjectService.applyChangesInOpenFiles (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:178459:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:179831:46)
    at /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:182024:96
    at Session.executeWithRequestId (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:182015:28)
    at Session.executeCommand (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:182024:41)
    at Session.onMessage (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:182052:35)
    at process.<anonymous> (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:186208:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
Info 18   [18:12:32.263] Failed to load module 'typescript-plugin-css-modules' from /home/v1rtl/.vscode-oss/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules: Error: Could not resolve JS module 'typescript-plugin-css-modules' starting at '/home/v1rtl/.vscode-oss/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules'. Looked in: /home/v1rtl/.vscode-oss/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules/typescript-plugin-css-modules/package.json, /home/v1rtl/.vscode-oss/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules/typescript-plugin-css-modules.js, /home/v1rtl/.vscode-oss/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules/typescript-plugin-css-modules.jsx, /home/v1rtl/.vscode-oss/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules/typescript-plugin-css-modules/index.js, /home/v1rtl/.vscode-oss/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules/typescript-plugin-css-modules/index.jsx, /home/v1rtl/.vscode-oss/extensions/node_modules/typescript-plugin-css-modules/package.json, /home/v1rtl/.vscode-oss/extensions/node_modules/typescript-plugin-css-modules.js, /home/v1rtl/.vscode-oss/extensions/node_modules/typescript-plugin-css-modules.jsx, /home/v1rtl/.vscode-oss/extensions/node_modules/typescript-plugin-css-modules/index.js, /home/v1rtl/.vscode-oss/extensions/node_modules/typescript-plugin-css-modules/index.jsx, /home/v1rtl/.vscode-oss/node_modules/typescript-plugin-css-modules/package.json, /home/v1rtl/.vscode-oss/node_modules/typescript-plugin-css-modules.js, /home/v1rtl/.vscode-oss/node_modules/typescript-plugin-css-modules.jsx, /home/v1rtl/.vscode-oss/node_modules/typescript-plugin-css-modules/index.js, /home/v1rtl/.vscode-oss/node_modules/typescript-plugin-css-modules/index.jsx, /home/v1rtl/node_modules/typescript-plugin-css-modules/package.json, /home/v1rtl/node_modules/typescript-plugin-css-modules.js, /home/v1rtl/node_modules/typescript-plugin-css-modules.jsx, /home/v1rtl/node_modules/typescript-plugin-css-modules/index.js, /home/v1rtl/node_modules/typescript-plugin-css-modules/index.jsx, /home/node_modules/typescript-plugin-css-modules/package.json, /home/node_modules/typescript-plugin-css-modules.js, /home/node_modules/typescript-plugin-css-modules.jsx, /home/node_modules/typescript-plugin-css-modules/index.js, /home/node_modules/typescript-plugin-css-modules/index.jsx, /node_modules/typescript-plugin-css-modules/package.json, /node_modules/typescript-plugin-css-modules.js, /node_modules/typescript-plugin-css-modules.jsx, /node_modules/typescript-plugin-css-modules/index.js, /node_modules/typescript-plugin-css-modules/index.jsx
    at Object.resolveJSModule (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:44257:19)
    at sys.require (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:185768:49)
    at Project.resolveModule (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:173477:35)
    at /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:174624:36
    at Object.firstDefined (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:221:26)
    at Project.beginEnablePluginSync (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:174623:41)
    at ProjectService.requestEnablePlugin (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:178808:49)
    at Project.enablePlugin (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:174687:37)
    at ConfiguredProject.enablePluginsWithOptions (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:175358:30)
    at ProjectService.loadConfiguredProject (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:177076:25)
    at ProjectService.createAndLoadConfiguredProject (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:177028:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:177033:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:178119:44)
    at /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:178459:97
    at Object.flatMap (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:524:25)
    at ProjectService.applyChangesInOpenFiles (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:178459:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:179831:46)
    at /usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:182024:96
    at Session.executeWithRequestId (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:182015:28)
    at Session.executeCommand (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:182024:41)
    at Session.onMessage (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:182052:35)
    at process.<anonymous> (/usr/lib/code/extensions/node_modules/typescript/lib/tsserver.js:186208:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

This `Error: Could not resolve JS module 'typescript-plugin-css-modules'` repeats with every extension.

**Comment by talentlessguy** [comment]
temporary solution is using alternative approach with recommended and setting a global vs code setting to include the plugin

**Comment by mariusGundersen** [comment]
from this line in your logs:

```
Failed to load module 'typescript-plugin-css-modules' from /home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0/node_modules: Error: Could not resolve JS module 'typescript-plugin-css-modules' starting at '/home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0/node_modules'
```

it seems like typescript is looking for the extension in the wrong place. This is probably because you haven't set vscode to use the workspace version of typescript. In the command prompt select the version from the workspace and it should be good to go.
![image](https://user-images.githubusercontent.com/464152/212851685-fd499af7-e6ad-4fd6-a962-b2dbfae662cc.png)
![image](https://user-images.githubusercontent.com/464152/212851765-a1b27e71-e982-4e61-a974-287c4016cea0.png)


It would be nice if there was a better way to notice this issue. I spent a few hours just now trying to get the plugin to work

**Comment by talentlessguy** [comment]
@mariusGundersen ty it worked!

**Comment by mariusGundersen** [comment]
Maybe the documentation could be updated? Or have a post install script or something that checks the vscode settings and either reports or changes them?

**Comment by talentlessguy** [comment]
I just checked again and it doesn't work anymore even with workspace version

**Comment by talentlessguy** [comment]
log:

```js
Info 11   [20:36:52.690] Loading global plugin typescript-deno-plugin
Info 12   [20:36:52.690] Enabling plugin typescript-deno-plugin from candidate paths: /home/v1rtl/Coding/ens/typescript-plugin-css-modules,/home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0,/home/v1rtl/.vscode-oss/extensions/jpoissonnier.vscode-styled-components-1.7.0,/home/v1rtl/.vscode-oss/extensions/visualstudioexptteam.vscodeintellicode-1.2.30,/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js/../../..
Info 13   [20:36:52.691] Loading typescript-deno-plugin from /home/v1rtl/Coding/ens/typescript-plugin-css-modules (resolved to /home/v1rtl/Coding/ens/typescript-plugin-css-modules/node_modules)
Info 14   [20:36:52.717] Loading typescript-deno-plugin from /home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0 (resolved to /home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0/node_modules)
Info 15   [20:36:52.724] INIT typescript-deno-plugin
Info 16   [20:36:52.726] Plugin validation succeeded
Info 17   [20:36:52.726] Loading global plugin typescript-styled-plugin
Info 18   [20:36:52.726] Enabling plugin typescript-styled-plugin from candidate paths: /home/v1rtl/Coding/ens/typescript-plugin-css-modules,/home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0,/home/v1rtl/.vscode-oss/extensions/jpoissonnier.vscode-styled-components-1.7.0,/home/v1rtl/.vscode-oss/extensions/visualstudioexptteam.vscodeintellicode-1.2.30,/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js/../../..
Info 19   [20:36:52.727] Loading typescript-styled-plugin from /home/v1rtl/Coding/ens/typescript-plugin-css-modules (resolved to /home/v1rtl/Coding/ens/typescript-plugin-css-modules/node_modules)
Info 20   [20:36:52.729] Loading typescript-styled-plugin from /home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0 (resolved to /home/v1rtl/.vscode-oss/extensions/denoland.vscode-deno-3.16.0/node_modules)
Info 21   [20:36:52.730] Loading typescript-styled-plugin from /home/v1rtl/.vscode-oss/extensions/jpoissonnier.vscode-styled-components-1.7.0 (resolved to /home/v1rtl/.vscode-oss/extensions/jpoissonnier.vscode-styled-components-1.7.0/node_modules)
Info 22   [20:36:52.731] Loading typescript-styled-plugin from /home/v1rtl/.vscode-oss/extensions/visualstudioexptteam.vscodeintellicode-1.2.30 (resolved to /home/v1rtl/.vscode-oss/extensions/visualstudioexptteam.vscodeintellicode-1.2.30/node_modules)
Info 23   [20:36:52.732] Loading typescript-styled-plugin from /home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js/../../.. (resolved to /home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/node_modules)
Info 24   [20:36:52.732] Failed to load module 'typescript-styled-plugin' from /home/v1rtl/Coding/ens/typescript-plugin-css-modules/node_modules: Error: Could not resolve JS module 'typescript-styled-plugin' starting at '/home/v1rtl/Coding/ens/typescript-plugin-css-modules/node_modules'. Looked in: /home/v1rtl/Coding/ens/typescript-plugin-css-modules/node_modules/typescript-styled-plugin/package.json, /home/v1rtl/Coding/ens/typescript-plugin-css-modules/node_modules/typescript-styled-plugin.js, /home/v1rtl/Coding/ens/typescript-plugin-css-modules/node_modules/typescript-styled-plugin.jsx, /home/v1rtl/Coding/ens/typescript-plugin-css-modules/node_modules/typescript-styled-plugin/index.js, /home/v1rtl/Coding/ens/typescript-plugin-css-modules/node_modules/typescript-styled-plugin/index.jsx, /home/v1rtl/Coding/ens/node_modules/typescript-styled-plugin/package.json, /home/v1rtl/Coding/ens/node_modules/typescript-styled-plugin.js, /home/v1rtl/Coding/ens/node_modules/typescript-styled-plugin.jsx, /home/v1rtl/Coding/ens/node_modules/typescript-styled-plugin/index.js, /home/v1rtl/Coding/ens/node_modules/typescript-styled-plugin/index.jsx, /home/v1rtl/Coding/node_modules/typescript-styled-plugin/package.json, /home/v1rtl/Coding/node_modules/typescript-styled-plugin.js, /home/v1rtl/Coding/node_modules/typescript-styled-plugin.jsx, /home/v1rtl/Coding/node_modules/typescript-styled-plugin/index.js, /home/v1rtl/Coding/node_modules/typescript-styled-plugin/index.jsx, /home/v1rtl/node_modules/typescript-styled-plugin/package.json, /home/v1rtl/node_modules/typescript-styled-plugin.js, /home/v1rtl/node_modules/typescript-styled-plugin.jsx, /home/v1rtl/node_modules/typescript-styled-plugin/index.js, /home/v1rtl/node_modules/typescript-styled-plugin/index.jsx, /home/node_modules/typescript-styled-plugin/package.json, /home/node_modules/typescript-styled-plugin.js, /home/node_modules/typescript-styled-plugin.jsx, /home/node_modules/typescript-styled-plugin/index.js, /home/node_modules/typescript-styled-plugin/index.jsx, /node_modules/typescript-styled-plugin/package.json, /node_modules/typescript-styled-plugin.js, /node_modules/typescript-styled-plugin.jsx, /node_modules/typescript-styled-plugin/index.js, /node_modules/typescript-styled-plugin/index.jsx
    at Object.resolveJSModule (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:44257:19)
    at sys.require (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:185768:49)
    at Project.resolveModule (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:173477:35)
    at /home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:174624:36
    at Object.firstDefined (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:221:26)
    at Project.beginEnablePluginSync (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:174623:41)
    at ProjectService.requestEnablePlugin (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:178808:49)
    at Project.enablePlugin (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:174687:37)
    at _loop_1 (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:174603:28)
    at Project.enableGlobalPlugins (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:174608:21)
    at ConfiguredProject.enablePluginsWithOptions (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:175361:29)
    at ProjectService.loadConfiguredProject (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:177076:25)
    at ProjectService.createAndLoadConfiguredProject (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:177028:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:177033:36)
    at ProjectService.assignProjectToOpenedScriptInfo (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:178119:44)
    at /home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:178459:97
    at Object.flatMap (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:524:25)
    at ProjectService.applyChangesInOpenFiles (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:178459:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:179831:46)
    at /home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:182024:96
    at Session.executeWithRequestId (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:182015:28)
    at Session.executeCommand (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:182024:41)
    at Session.onMessage (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:182052:35)
    at process.<anonymous> (/home/v1rtl/Coding/ens/node_modules/.pnpm/typescript@4.9.4/node_modules/typescript/lib/tsserver.js:186208:31)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by mrmckeb** [comment]
Hi there, the instructions in the README do say that you need to load the workspace version of TypeScript - as @mariusGundersen suggested - but if it's still not working after that, there may be some other configuration issue.

Are you able to share a reproduction? I couldn't reproduce with the steps provided - I also run this in several Next.js projects with pnpm, including in a monorepo.

**Comment by mrmckeb** [comment]
No problem, thanks for updating this!
