### ISSUE TITLE
Plugin fails when importing using absolute tilde imports inside an imported SCSS module file

### ISSUE THREAD

**Issue by evankennedy** [mrmckeb/typescript-plugin-css-modules#82]
**Describe the bug**
Inside an SCSS file you've imported from a TS file, if you import a global SCSS file using `~src/...`, the import works, but if that global imported SCSS file imports another global SCSS file, that second import will fail. I know a relative import would work, but in my use case the files are actually pretty far apart.

**To Reproduce**

Repo here with existing issue: https://github.com/evankennedy/ts-plugin-css-modules-absolute-import

You can see the issue go away if you comment out the line in `src/theme/_other.scss`

Steps:
1. Add two global scss files.
2. Import the first from the second.
3. Import the second from another file.

**Expected behavior**
The imports would be successful.

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: Ubuntu 19.10
- Browser: None
- Version: N/A
- Editor: VS Code

**Additional context**

```
Info 318  [19:29:42.494] [typescript-plugin-css-modules] Failed Error: Can't find stylesheet to import.
  ╷
2 │ @import '~src/theme/second';
  │         ^^^^^^^^^^^^^^^^^^^^
  ╵
  src/theme/_other.scss 2:9  @import
  stdin 2:9                  root stylesheet
Info 319  [19:29:42.495] [typescript-plugin-css-modules] Stack trace: Error: Can't find stylesheet to import.
  ╷
2 │ @import '~src/theme/second';
  │         ^^^^^^^^^^^^^^^^^^^^
  ╵
  src/theme/_other.scss 2:9  @import
  stdin 2:9                  root stylesheet
    at Object._newRenderError (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/sass/sass.dart.js:13621:19)
    at Object._wrapException (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/sass/sass.dart.js:13467:16)
    at StaticClosure._renderSync (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/sass/sass.dart.js:13442:18)
    at Object.Primitives_applyFunction (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/sass/sass.dart.js:1064:30)
    at Object.Function_apply (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/sass/sass.dart.js:4898:16)
    at _callDartFunctionFast (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/sass/sass.dart.js:6580:16)
    at Object.renderSync (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/sass/sass.dart.js:6558:18)
    at Object.exports.getClasses (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript-plugin-css-modules/lib/helpers/getClasses.js:71:18)
    at Object.exports.getDtsSnapshot (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript-plugin-css-modules/lib/helpers/getDtsSnapshot.js:15:32)
    at Object.ts.updateLanguageServiceSourceFile (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript-plugin-css-modules/lib/index.js:111:51)
    at acquireOrUpdateDocument (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:112216:43)
    at Object.updateDocumentWithKey (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:112182:20)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:135296:49)
    at tryReuseStructureFromOldProgram (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:98176:28)
    at Object.createProgram (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:97765:30)
    at synchronizeHostData (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:135218:26)
    at Proxy.getProgram (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:135310:13)
    at ConfiguredProject.Project.updateGraphWorker (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:139786:53)
    at ConfiguredProject.Project.updateGraph (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:139729:42)
    at ConfiguredProject.updateGraph (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:140654:63)
    at Object.updateProjectIfDirty (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:141076:45)
    at checkOne (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:144834:28)
    at MultistepOperation.executeAction (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:143950:25)
    at /home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:143940:100
    at IOSession.Session.executeWithRequestId (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:145994:28)
    at Object.executeWithRequestId (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:144583:87)
    at Timeout._onTimeout (/home/evan/projects/ts-plugin-css-modules-absolute-import/node_modules/typescript/lib/tsserver.js:143940:41)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

Let me know if you need any more info!

**Comment by mrmckeb** [comment]
Hi @evankennedy, thanks for taking the time to raise this.

From my understanding, the `tilde` is meant for imports from `node_modules`, not from other directories - which is working right now. It's also something that is not supported by Sass itself, but instead the loader for Webpack (as I understand). This could be why Sass is failing - this error is definitely coming from Sass, and not from this library.

You can provide your own importer to Sass, but this is not something I've tested yet. Here's one that should allow tildes, but again, for `node_modules`:
https://www.npmjs.com/package/node-sass-tilde-importer

We do support relative paths, and you can even set your own paths using our `rendererOptions`:
https://github.com/mrmckeb/typescript-plugin-css-modules#rendererOptions

I'm not sure we can fix this, but if you have some ideas, please let me know - and we always welcome PRs!

**Comment by abeMedia** [comment]
@mrmckeb how about just adding an example to the README on how this can be achieved using either rendererOptions or an importer?
I think it's quite a common thing to use tilde imports in SCSS files.

**Comment by mrmckeb** [comment]
Thanks @abeMedia, I'd love a pull request if you'd be interested in putting that together?

**Comment by abeMedia** [comment]
Sure thing. Should have time to do this next week.
